name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Library on ${{ matrix.os }} and GCC ${{ matrix.gcc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            gcc: 8
    env:
      build_dir: "build"
      config: "Release"

    steps:
      - uses: actions/checkout@v2

      - name: Install CUDA
        run: |
          sudo apt-get update
          sudo apt-get install nvidia-cuda-toolkit
          sudo apt-get install nvidia-cuda-dev
          nvcc -V

      - name: Install and configure GCC and GXX
        run: |
          sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
          echo "::set-env name=CC::/usr/bin/gcc-${{ matrix.gcc }}"
          echo "::set-env name=CXX::/usr/bin/g++-${{ matrix.gcc }}"
          echo "::set-env name=CUDAHOSTCXX::/usr/bin/g++-${{ matrix.gcc }}"

      - name: Configure CMake build
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCUBOOL_BUILD_TESTS=YES

      - name: Build library sources
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j `nproc`



